version: '3.7'

services:
  nginx:
    image: nginx:1.24
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 1000m
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:8080"
    networks:
      - default
    restart: unless-stoped