version: '3.7'

services:
  nginx:
    networks:
      - default
    image: "nginx:1.24"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf